
backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
public_folder: "/uploads" 

collections:
  - name: 'products'
    label: 'Products'
    folder: 'products'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Release', name: 'release', widget: 'string' }
      - { label: 'View', name: 'view', widget: 'string'}
      - { label: 'Code', name: 'code', widget: 'string' }
      - { label: 'Genre', name: 'genre', widget: 'string'}
      - { label: 'Ranking', name: 'ranking', widget: 'string'}
      - { label: 'Tags', name: 'tags', widget: 'list'}
  - label: 'Galeria', 
    name: 'galeria', 
    widget: 'image', 
    required: 'false'
    media_library:
      name: cloudinary
      config:
        cloud_name: uayeb
        api_key: 326796926479962
        multiple: true       
              