
backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_library:
  name: cloudinary
  config:
    cloud_name: uayeb
    api_key: 326796926479962
    multiple: false

collections:
  - name: 'categorias'
    label: 'Categorias'
    folder: 'categorias'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'ID', name: 'id', widget: 'id'}
      - { label: 'Imagen', name: 'imagen', widget: 'image'}

  - name: 'marcas'
    label: 'Marcas'
    folder: 'marcas'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string'}
      - { label: 'Imagen', name: 'imagen', widget: 'image'}    

  - name: 'servicios'
    label: 'Servicios'
    folder: 'servicios'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string'}
      - { label: 'Imagen',name: 'imagen', widget: 'image'}
      - { label: 'Servicio', name: 'servicio', widget: 'list'}  

  - name: 'soluciones'
    label: 'Soluciones'
    folder: 'soluciones'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string'}
      - { label: 'Nombre', name: 'nombre', widget: 'string'}
      - { label: 'Descripcion', name: 'descripcion', widget: 'string'}
      - { label: 'Imagen', name: 'imagen', widget: 'image'}

  - name: 'headend'
    label: 'Headend'
    folder: 'headend'
    create: true
    slug: '{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string'}
      - { label: 'ID', name: 'id', widget: 'id'}
      - { label: 'Imange', name: 'imagen', widget: 'image'}
      - label: 'Ficha'
        name: 'ficha'
        widget: 'file'
        media_folder: "static/uploads"
        public_folder: "/uploads"
     -  label: 'Categorias'
        name: 'categorias'
        collection: 'categorias'
        searchFields: ['title']
        displayFields: ['title']
        valuedField: 'id'   


        
              