
backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_library:
  name: cloudinary
  config:
    cloud_name: uayeb
    api_key: 326796926479962
    multiple: true

collections:
  - name: 'products'
    label: 'Products'
    folder: 'products'
    create: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: false }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Release', name: 'release', widget: 'string' }
      - { label: 'View', name: 'view', widget: 'string'}
      - { label: 'Code', name: 'code', widget: 'string' }
      - { label: 'Genre', name: 'genre', widget: 'string'}
      - { label: 'Ranking', name: 'ranking', widget: 'string'}
      - { label: 'Tags', name: 'tags', widget: 'list'}
      - { label: 'Imagen', name: 'imagen', widget: 'image'}
      - { label: 'Galeria', name: 'galeria', widget: 'image'}        
        
              